name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04  # Você pode alterar para a versão mais recente, se preferir

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@5.0.0  # Atualizado para a versão 5.0.0
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Diretório local do código
          server-dir: public_html  # Diretório no servidor FTP
