name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: "77.37.127.102"        # Endereço do servidor FTP
          username: "u920731321.fstarck"  # Nome de usuário do FTP
          password: "2yI^>/|$"        # Senha do FTP
          local-dir: "./"                  # Diretório local do código
          server-dir: "public_html/"       # Diretório no servidor FTP
